package com.silq.ai.backend.services.llm;

/**
 * Defines the contract for a generic Large Language Model (LLM) service.
 *
 * This interface allows for multiple LLM implementations (e.g., OpenAI, Gemini)
 * to be used interchangeably through the `LLMProxyFactory`.
 */
public interface LLMService {

    /**
     * Generates a response from the LLM based on a user prompt.
     *
     * @param engineeredPrompt The processed prompt ready for AI consumption.
     * @param userApiKey The API key for authenticating with the LLM provider.
     * @return The response content generated by the LLM.
     */
    String generateResponse(String engineeredPrompt, String userApiKey);
}
